version: '3.7'

services:

  server:
    container_name: myfastapi
    build:
      context: .
      dockerfile: ./debug.Dockerfile
    restart: always
    volumes:
      - ./src:/src
    expose:
      - "8000"
      - "5678"
    ports:
      - 8000:8000
      - 5678:5678
