version: '3.7'

services:

  server:
    container_name: myfastapi
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    volumes:
      - ./src:/src
    expose:
      - "8000"
    ports:
      - 8000:8000
